# Generated by Django 3.2.5 on 2021-07-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_img',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
