# Generated by Django 3.2.5 on 2021-08-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_category_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='temptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_data', models.TextField(null=True)),
            ],
        ),
    ]
